### ISSUE TITLE
[BUG] set_scene only works towards menu screens

### ISSUE THREAD

**Issue by orbiroboti** [harbingerofme/RoR2Cheats#23]
When utilizing the set_scene command, calls with it made to either map name, map name with file format included, or ID corresponded by command "scene_list" don't function bar for these exceptions:
   - title
   - logbook
   - crystalworld (prismatic-trial menu)

Getting into these requires the former way of using set_scene (just listing off the map name) but are the only way to actually use set_scene - both in-game (properly playing) and out.

Works without any other mod (save for the big two) enabled; current mod list is attached regardless.
![plugins_2019-10-15_18-01-55](https://user-images.githubusercontent.com/56612712/66876048-fe68bd80-ef75-11e9-8eed-7511f7426d4a.png)

**Comment by Paddywaan** [comment]
use `next_stage {stagename}`

**Comment by orbiroboti** [comment]
next_scene does work properly; I am officially confirmed a silly. Thank you!
