### ISSUE TITLE
Change Command: list_ai; list_body: UI for in-game console stops at 27/50 (respectively)

### ISSUE THREAD

**Issue by orbiroboti** [harbingerofme/RoR2Cheats#24]
Although it parses perfectly fine (as shown by the console menu outside game), list_ai and list_body always stop - with no option to go up - at 27/50 for the id list, respectively (ImpOverlord;MercBody) An example of this can be seen attached to this post.
![Risk_of_Rain_2_2019-10-15_18-08-29](https://user-images.githubusercontent.com/56612712/66876315-fd845b80-ef76-11e9-8583-abc29314be0e.png)

It's less of an absolute fix and more a convenience, as the old list didn't quite have this problem (as far as I remember?). It just sorta ate up console with the output, is all.

It'll simply save an alt-tab, so if it cannot be messed around with/adjusted, then it's little loss.

**Comment by Paddywaan** [comment]
As far as I'm aware, the console cannot be moved as per default. We are maybe planning some console enhancements so this could be bundled into those. Having the ability to properly scroll the console would be great.

**Comment by harbingerofme** [comment]
Console is limited to 25 messages, we can change this limit quite a bit,
but this particular issue should be resolved with emitting a long steing
instead of 75 messages.
