### ISSUE TITLE
[BUG] no_enemies doesn't stop enemies from spawning

### ISSUE THREAD

**Issue by orbiroboti** [harbingerofme/RoR2Cheats#25]
This time, I've gotcha...!

After using the no_enemies command in conjunction with the kill_all command to create an enemy-free zone, spawncards and the like will still go through, regardless. You can see it in action here: https://streamable.com/mh9ig. The console viewage was just to potentially catch what I assumed was possibly connected to this phenomena (ie: the first attached image; if not in order: the image depicting console and nothing else)
![BepInEx_5 0 0 0_-_Risk_of_Rain_2_2019-10-15_17-17-38](https://user-images.githubusercontent.com/56612712/66877473-31618000-ef7b-11e9-8ce1-f3493bc7b114.png), but enemies seemingly still spawn, regardless.

All scenes are affected by this as far as I've noticed, as no enemies are pretty much omitted from spawning while the command is enabled. My mod-list is still the same:
![plugins_2019-10-15_18-01-55](https://user-images.githubusercontent.com/56612712/66877502-4e964e80-ef7b-11e9-93ad-498d2e3a078b.png), but I went in to test if this still happened without influence from the likes of "FirstStageEnemySpawns" and whatever possibly else, and it still did, as shown in this 
image of a Lemurian fleeing from my god-like presence wondering why he's managed to obtain a materialistic form: 
![Risk_of_Rain_2_2019-10-15_18-29-27](https://user-images.githubusercontent.com/56612712/66877542-7980a280-ef7b-11e9-96d7-8dbe0898d398.png)

**Comment by harbingerofme** [comment]
Could be a case of conflicting IL. I'll investigate tomorrow/see if there's On solutions available.

**Comment by harbingerofme** [comment]
Fixed in 7e7a0cbd8affe80cfd6f41e99b637a6998615313
