### ISSUE TITLE
kill_all no longer demeans you for committing mass genocide

### ISSUE THREAD

**Issue by orbiroboti** [harbingerofme/RoR2Cheats#26]
kill_all no longer calls you a monster for having killed everything in the map in one fell swoop. This loss of flavor text to make me reflect on my actions is absolutely integral to the ror2cheats experience. Absolutely.

**Comment by harbingerofme** [comment]
Intended. Won't fix. You don't get xp or money for it, therefore you aren't
a monster.

**Comment by orbiroboti** [comment]
Damn your sound logic!
