### ISSUE TITLE
Use change_team's acceptance of more than one style of value "universal" (was previously: Change Command change_team to accept team names instead of only values)

### ISSUE THREAD

**Issue by orbiroboti** [harbingerofme/RoR2Cheats#27]
EDIT: changed the statement to more coincide in line with this being kept open and made "non-priority" by Harb to ask for a universal concept off a previously misunderstood post relating to change_team. That post'll be kept for posterity's sake below, but focus towards current topic is showcased in said original topic around last paragraph, and should be used concurrently as the subject matter (because am big dum-dum)

A simple enough quality-of-life: it's a bit cumbersome just allotting only values that don't really have definition for them nor is there a helper for when you input the code wrong to help things along. It's better than it used to be (and actually functions now, yay for teammates!)

![Risk_of_Rain_2_2019-10-15_17-07-15](https://user-images.githubusercontent.com/56612712/66877912-21e33680-ef7d-11e9-96f0-ebd0e07c7759.png)

but even still, it could make for more convenience and fit along into the same sort of ID-list that goes on for other commands when you fail to input something. Could also help to make things more universal potentially (since ID's are no longer necessary with the likes of give_item and give_equipment) as well.

**Said last paragraph, as stated above in the edited statement:** Could also do the inverse and have them both be used - the values and the statements - and allot the same for the other commands. Give a legacy setting of sorts for people who know some values off the top of their heads, but that's just brainstorming in essence. Not entirely needed - just convenience.

**Comment by harbingerofme** [comment]
Teamnames should be supported and are "neutral", "player", and "monster"

**Comment by orbiroboti** [comment]
Ahh, it does, actually. Odd, it wasn't quite doing it for me before for whatever reason while I was a golem. I'll try to recreate it if possible, but otherwise, it's simply my mistake.

**Comment by harbingerofme** [comment]
Issue continued in #34
