### ISSUE TITLE
Add special character stripping for language invariants

### ISSUE THREAD

**Issue by harbingerofme** [harbingerofme/RoR2Cheats#29]
Remove special characters such as spaces and `-` and ``' from strings.

**Comment by Paddywaan** [comment]
Implemented character stripping:
[Info   : Unity Log] Syringe:SoldiersSyringe:ASDF
[Info   : Unity Log] Bear:TougherTimes:ASDF
[Info   : Unity Log] Behemoth:BrilliantBehemoth:ASDF
[Info   : Unity Log] Missile:AtGMissileMk.1:ASDF
[Info   : Unity Log] ExplodeOnDeath:Willothewisp:ASDF
[Info   : Unity Log] Dagger:CeremonialDagger:ASDF
[Info   : Unity Log] Tooth:MonsterTooth:ASDF
[Info   : Unity Log] CritGlasses:LensMakersGlasses:ASDF
[Info   : Unity Log] Hoof:PaulsGoatHoof:ASDF
[Info   : Unity Log] Feather:HopooFeather:ASDF
[Info   : Unity Log] AACannon:ITEM_AACANNON_NAME:ASDF
[Info   : Unity Log] ChainLightning:Ukulele:ASDF
[Info   : Unity Log] PlasmaCore:ITEM_PLASMACORE_NAME:ASDF
[Info   : Unity Log] Seed:LeechingSeed:ASDF
[Info   : Unity Log] Icicle:FrostRelic:ASDF
[Info   : Unity Log] GhostOnKill:HappiestMask:ASDF
[Info   : Unity Log] Mushroom:BustlingFungus:ASDF
[Info   : Unity Log] Crowbar:Crowbar:ASDF
[Info   : Unity Log] LevelBonus:ITEM_LEVELBONUS_NAME:ASDF
[Info   : Unity Log] AttackSpeedOnCrit:PredatoryInstincts:ASDF
[Info   : Unity Log] BleedOnHit:TriTipDagger:ASDF
[Info   : Unity Log] SprintOutOfCombat:RedWhip:ASDF
[Info   : Unity Log] FallBoots:H3AD5Tv2:ASDF
[Info   : Unity Log] CooldownOnCrit:WickedRing:ASDF
[Info   : Unity Log] WardOnLevel:Warbanner:ASDF
[Info   : Unity Log] Phasing:OldWarStealthkit:ASDF
[Info   : Unity Log] HealOnCrit:HarvestersScythe:ASDF
[Info   : Unity Log] HealWhileSafe:CautiousSlug:ASDF
[Info   : Unity Log] TempestOnKill:ITEM_TEMPESTONKILL_NAME:ASDF
[Info   : Unity Log] PersonalShield:PersonalShieldGenerator:ASDF
[Info   : Unity Log] EquipmentMagazine:FuelCell:ASDF
[Info   : Unity Log] NovaOnHeal:NkuhanasOpinion:ASDF
[Info   : Unity Log] ShockNearby:UnstableTeslaCoil:ASDF
[Info   : Unity Log] Infusion:Infusion:ASDF
[Info   : Unity Log] WarCryOnCombat:ITEM_WARCRYONCOMBAT_NAME:ASDF
[Info   : Unity Log] Clover:57LeafClover:ASDF
[Info   : Unity Log] Medkit:Medkit:ASDF
[Info   : Unity Log] Bandolier:Bandolier:ASDF
[Info   : Unity Log] BounceNearby:SentientMeatHook:ASDF
[Info   : Unity Log] IgniteOnKill:Gasoline:ASDF
[Info   : Unity Log] PlantOnHit:ITEM_PLANTONHIT_NAME:ASDF
[Info   : Unity Log] StunChanceOnHit:StunGrenade:ASDF
[Info   : Unity Log] Firework:BundleofFireworks:ASDF
[Info   : Unity Log] LunarDagger:ShapedGlass:ASDF
[Info   : Unity Log] GoldOnHit:BrittleCrown:ASDF
[Info   : Unity Log] MageAttunement:ITEM_MAGEATTUNEMENT_NAME:ASDF
[Info   : Unity Log] WarCryOnMultiKill:BerzerkersPauldron:ASDF
[Info   : Unity Log] BoostHp:ITEM_BOOSTHP_NAME:ASDF
[Info   : Unity Log] BoostDamage:ITEM_BOOSTDAMAGE_NAME:ASDF
[Info   : Unity Log] ShieldOnly:Transcendence:ASDF
[Info   : Unity Log] AlienHead:AlienHead:ASDF
[Info   : Unity Log] Talisman:SoulboundCatalyst:ASDF
[Info   : Unity Log] Knurl:TitanicKnurl:ASDF
[Info   : Unity Log] BeetleGland:QueensGland:ASDF
[Info   : Unity Log] BurnNearby:ITEM_BURNNEARBY_NAME:ASDF
[Info   : Unity Log] CritHeal:ITEM_CRITHEAL_NAME:ASDF
[Info   : Unity Log] CrippleWardOnLevel:ITEM_CRIPPLEWARDONLEVEL_NAME:ASDF
[Info   : Unity Log] SprintBonus:EnergyDrink:ASDF
[Info   : Unity Log] SecondarySkillMagazine:BackupMagazine:ASDF
[Info   : Unity Log] StickyBomb:StickyBomb:ASDF
[Info   : Unity Log] TreasureCache:RustedKey:ASDF
[Info   : Unity Log] BossDamageBonus:ArmorPiercingRounds:ASDF
[Info   : Unity Log] SprintArmor:RoseBuckler:ASDF
[Info   : Unity Log] IceRing:RunaldsBand:ASDF
[Info   : Unity Log] FireRing:KjarosBand:ASDF
[Info   : Unity Log] SlowOnHit:Chronobauble:ASDF
[Info   : Unity Log] ExtraLife:DiosBestFriend:ASDF
[Info   : Unity Log] ExtraLifeConsumed:DiosBestFriend(Consumed):ASDF
[Info   : Unity Log] UtilitySkillMagazine:HardlightAfterburner:ASDF
[Info   : Unity Log] HeadHunter:WakeofVultures:ASDF
[Info   : Unity Log] KillEliteFrenzy:Brainstalks:ASDF
[Info   : Unity Log] RepeatHeal:Corpsebloom:ASDF
[Info   : Unity Log] Ghost:ITEM_GHOST_NAME:ASDF
[Info   : Unity Log] HealthDecay:ITEM_HEALTHDECAY_NAME:ASDF
[Info   : Unity Log] AutoCastEquipment:GestureoftheDrowned:ASDF
[Info   : Unity Log] IncreaseHealing:RejuvenationRack:ASDF
[Info   : Unity Log] JumpBoost:WaxQuail:ASDF
[Info   : Unity Log] DrizzlePlayerHelper:ITEM_DRIZZLEPLAYERHELPER_NAME:ASDF
[Info   : Unity Log] ExecuteLowHealthElite:OldGuillotine:ASDF
[Info   : Unity Log] EnergizedOnEquipmentUse:WarHorn:ASDF
[Info   : Unity Log] BarrierOnOverHeal:Aegis:ASDF
[Info   : Unity Log] TonicAffliction:TonicAffliction:ASDF
[Info   : Unity Log] TitanGoldDuringTP:HalcyonSeed:ASDF
[Info   : Unity Log] SprintWisp:LittleDisciple:ASDF
[Info   : Unity Log] BarrierOnKill:TopazBrooch:ASDF
[Info   : Unity Log] ArmorReductionOnHit:ShatteringJustice:ASDF
[Info   : Unity Log] TPHealingNova:LeptonDaisy:ASDF
[Info   : Unity Log] NearbyDamageBonus:FocusCrystal:ASDF
[Info   : Unity Log] LunarUtilityReplacement:StridesofHeresy:ASDF
[Info   : Unity Log] MonsoonPlayerHelper:ITEM_MONSOONPLAYERHELPER_NAME:ASDF
[Info   : Unity Log] Syringe:SoldiersSyringe:ASDF
[Info   : Unity Log] Bear:TougherTimes:ASDF
[Info   : Unity Log] Behemoth:BrilliantBehemoth:ASDF
[Info   : Unity Log] Missile:AtGMissileMk.1:ASDF
[Info   : Unity Log] ExplodeOnDeath:Willothewisp:ASDF
[Info   : Unity Log] Dagger:CeremonialDagger:ASDF
[Info   : Unity Log] Tooth:MonsterTooth:ASDF
[Info   : Unity Log] CritGlasses:LensMakersGlasses:ASDF
[Info   : Unity Log] Hoof:PaulsGoatHoof:ASDF
[Info   : Unity Log] Feather:HopooFeather:ASDF
[Info   : Unity Log] AACannon:ITEM_AACANNON_NAME:ASDF
[Info   : Unity Log] ChainLightning:Ukulele:ASDF
[Info   : Unity Log] PlasmaCore:ITEM_PLASMACORE_NAME:ASDF
[Info   : Unity Log] Seed:LeechingSeed:ASDF
[Info   : Unity Log] Icicle:FrostRelic:ASDF
[Info   : Unity Log] GhostOnKill:HappiestMask:ASDF
[Info   : Unity Log] Mushroom:BustlingFungus:ASDF
[Info   : Unity Log] Crowbar:Crowbar:ASDF
[Info   : Unity Log] LevelBonus:ITEM_LEVELBONUS_NAME:ASDF
[Info   : Unity Log] AttackSpeedOnCrit:PredatoryInstincts:ASDF
[Info   : Unity Log] BleedOnHit:TriTipDagger:ASDF
[Info   : Unity Log] SprintOutOfCombat:RedWhip:ASDF
[Info   : Unity Log] FallBoots:H3AD5Tv2:ASDF
[Info   : Unity Log] CooldownOnCrit:WickedRing:ASDF
[Info   : Unity Log] WardOnLevel:Warbanner:ASDF
[Info   : Unity Log] Phasing:OldWarStealthkit:ASDF
[Info   : Unity Log] HealOnCrit:HarvestersScythe:ASDF
[Info   : Unity Log] HealWhileSafe:CautiousSlug:ASDF
[Info   : Unity Log] TempestOnKill:ITEM_TEMPESTONKILL_NAME:ASDF
[Info   : Unity Log] PersonalShield:PersonalShieldGenerator:ASDF
[Info   : Unity Log] EquipmentMagazine:FuelCell:ASDF
[Info   : Unity Log] NovaOnHeal:NkuhanasOpinion:ASDF
[Info   : Unity Log] ShockNearby:UnstableTeslaCoil:ASDF
[Info   : Unity Log] Infusion:Infusion:ASDF
[Info   : Unity Log] WarCryOnCombat:ITEM_WARCRYONCOMBAT_NAME:ASDF
[Info   : Unity Log] Clover:57LeafClover:ASDF
[Info   : Unity Log] Medkit:Medkit:ASDF
[Info   : Unity Log] Bandolier:Bandolier:ASDF
[Info   : Unity Log] BounceNearby:SentientMeatHook:ASDF
[Info   : Unity Log] IgniteOnKill:Gasoline:ASDF
[Info   : Unity Log] PlantOnHit:ITEM_PLANTONHIT_NAME:ASDF
[Info   : Unity Log] StunChanceOnHit:StunGrenade:ASDF
[Info   : Unity Log] Firework:BundleofFireworks:ASDF
[Info   : Unity Log] LunarDagger:ShapedGlass:ASDF
[Info   : Unity Log] GoldOnHit:BrittleCrown:ASDF
[Info   : Unity Log] MageAttunement:ITEM_MAGEATTUNEMENT_NAME:ASDF
[Info   : Unity Log] WarCryOnMultiKill:BerzerkersPauldron:ASDF
[Info   : Unity Log] BoostHp:ITEM_BOOSTHP_NAME:ASDF
[Info   : Unity Log] BoostDamage:ITEM_BOOSTDAMAGE_NAME:ASDF
[Info   : Unity Log] ShieldOnly:Transcendence:ASDF
[Info   : Unity Log] AlienHead:AlienHead:ASDF
[Info   : Unity Log] Talisman:SoulboundCatalyst:ASDF
[Info   : Unity Log] Knurl:TitanicKnurl:ASDF
[Info   : Unity Log] BeetleGland:QueensGland:ASDF
[Info   : Unity Log] BurnNearby:ITEM_BURNNEARBY_NAME:ASDF
[Info   : Unity Log] CritHeal:ITEM_CRITHEAL_NAME:ASDF
[Info   : Unity Log] CrippleWardOnLevel:ITEM_CRIPPLEWARDONLEVEL_NAME:ASDF
[Info   : Unity Log] SprintBonus:EnergyDrink:ASDF
[Info   : Unity Log] SecondarySkillMagazine:BackupMagazine:ASDF
[Info   : Unity Log] StickyBomb:StickyBomb:ASDF
[Info   : Unity Log] TreasureCache:RustedKey:ASDF
[Info   : Unity Log] BossDamageBonus:ArmorPiercingRounds:ASDF
[Info   : Unity Log] SprintArmor:RoseBuckler:ASDF
[Info   : Unity Log] IceRing:RunaldsBand:ASDF
[Info   : Unity Log] FireRing:KjarosBand:ASDF
[Info   : Unity Log] SlowOnHit:Chronobauble:ASDF
[Info   : Unity Log] ExtraLife:DiosBestFriend:ASDF
[Info   : Unity Log] ExtraLifeConsumed:DiosBestFriend(Consumed):ASDF
[Info   : Unity Log] UtilitySkillMagazine:HardlightAfterburner:ASDF
[Info   : Unity Log] HeadHunter:WakeofVultures:ASDF
[Info   : Unity Log] KillEliteFrenzy:Brainstalks:ASDF
[Info   : Unity Log] RepeatHeal:Corpsebloom:ASDF
[Info   : Unity Log] Ghost:ITEM_GHOST_NAME:ASDF
[Info   : Unity Log] HealthDecay:ITEM_HEALTHDECAY_NAME:ASDF
[Info   : Unity Log] AutoCastEquipment:GestureoftheDrowned:ASDF
[Info   : Unity Log] IncreaseHealing:RejuvenationRack:ASDF
[Info   : Unity Log] JumpBoost:WaxQuail:ASDF
[Info   : Unity Log] DrizzlePlayerHelper:ITEM_DRIZZLEPLAYERHELPER_NAME:ASDF
[Info   : Unity Log] ExecuteLowHealthElite:OldGuillotine:ASDF
[Info   : Unity Log] EnergizedOnEquipmentUse:WarHorn:ASDF
[Info   : Unity Log] BarrierOnOverHeal:Aegis:ASDF
[Info   : Unity Log] TonicAffliction:TonicAffliction:ASDF
[Info   : Unity Log] TitanGoldDuringTP:HalcyonSeed:ASDF
[Info   : Unity Log] SprintWisp:LittleDisciple:ASDF
[Info   : Unity Log] BarrierOnKill:TopazBrooch:ASDF
[Info   : Unity Log] ArmorReductionOnHit:ShatteringJustice:ASDF
[Info   : Unity Log] TPHealingNova:LeptonDaisy:ASDF
[Info   : Unity Log] NearbyDamageBonus:FocusCrystal:ASDF
[Info   : Unity Log] LunarUtilityReplacement:StridesofHeresy:ASDF
[Info   : Unity Log] MonsoonPlayerHelper:ITEM_MONSOONPLAYERHELPER_NAME:ASDF
[Info   : Unity Log] Null
