### ISSUE TITLE
New Command: <kick/ban> {playernamepartial}

### ISSUE THREAD

**Issue by Paddywaan** [harbingerofme/RoR2Cheats#37]
parse the playername partial and ensure only a single match is returned before kicking. Amiguous needs to return error. Vanilla behaviour requires player ID

**Comment by harbingerofme** [comment]
Is this permanent banning?
Seems more like a thing for a multiplayer mod.

**Comment by Paddywaan** [comment]
Session ban. its literally just an interface for the already existing commands, turning a process of two commands into a single command, instead of requiring listing players prior to issueing the kick/ban to provide the playerid

**Comment by harbingerofme** [comment]
We could overwrite kick to check usernames/ids too. I do not consider this outside the scope.
