### ISSUE TITLE
New Command: <family_event> {randomoccurance|CharacterType?}

### ISSUE THREAD

**Issue by Paddywaan** [harbingerofme/RoR2Cheats#38]
Investigate the charactermaster families & random events, possible to the extent that these can be scheduled via a command or a given charactermaster which will then return a family to schedule the event around. Name needs work.

**Comment by Paddywaan** [comment]
Did not manage to find an ideal method to specify an event, again stage specific due to CurrentStageInfo. Perhaps use similar method to set_boss if value:effort deemed appropriate. Issue may be reopened for later release.

**Comment by harbingerofme** [comment]
We'll maybe change it to `force_event`. And just force a one time event instead.
