### ISSUE TITLE
New command: give_lunar [count def 1]

### ISSUE THREAD

**Issue by Paddywaan** [harbingerofme/RoR2Cheats#42]
Does what it says on the tin?

**Comment by harbingerofme** [comment]
it's not an item. Change it to give_lunar [amount].

 One major concern I have is that people will use it to give other players an insane or negative amount of lunar coins, ruining their save. So are we making it so that players can't give/take others coins?

**Comment by Paddywaan** [comment]
Hmm, good point. We could just enforce non-negative resultant values. and permit the manipualtion of all clients coins. My loonercoins mod basically "steals" them anyway. I don't specifically have anything against removing coins from players during an instance, however corruption of save must be avoided.

I'll hold off on implementation until a conclusion is reached

**Comment by harbingerofme** [comment]
Since #17 can spawn coins for other players anyway, I'm restricting the scope to only the submitting user.
