### ISSUE TITLE
for the love of god use StringBuilder

### ISSUE THREAD

**Issue by mistername** [harbingerofme/RoR2Cheats#45]
https://github.com/harbingerofme/RoR2Cheats/blob/e7e882b8aa1104da7305eb6b05fde9a77bb8ee2e/Cheats.cs#L130
https://github.com/harbingerofme/RoR2Cheats/blob/e7e882b8aa1104da7305eb6b05fde9a77bb8ee2e/Cheats.cs#L116
these functions are inefficient, please use StringBuilder

**Comment by harbingerofme** [comment]
130 resolved.
