### ISSUE TITLE
Incorrect description seed command

### ISSUE THREAD

**Issue by mistername** [harbingerofme/RoR2Cheats#46]
https://github.com/harbingerofme/RoR2Cheats/blob/e7e882b8aa1104da7305eb6b05fde9a77bb8ee2e/Cheats.cs#L532
it can also get the seed if here are no arguments so the discription is false, fuck your shit paddy

**Comment by mistername** [comment]
also here:
https://github.com/harbingerofme/RoR2Cheats/blob/e7e882b8aa1104da7305eb6b05fde9a77bb8ee2e/Cheats.cs#L563

**Comment by mistername** [comment]
also here:
https://github.com/harbingerofme/RoR2Cheats/blob/e7e882b8aa1104da7305eb6b05fde9a77bb8ee2e/Cheats.cs#L613

**Comment by harbingerofme** [comment]
- [ ] seed
- [ ] fixed_time
- [ ] stage_clear_count
