### ISSUE TITLE
Take a look at what the hell that character list in character.cs is

### ISSUE THREAD

**Issue by harbingerofme** [harbingerofme/RoR2Cheats#7]
WTF is that, why does it exist, and do we need to maintain it?

**Comment by Paddywaan** [comment]
match against localised string of prefab bodies instead, possibly maintain allowance for shorthands.

**Comment by harbingerofme** [comment]
Fixed in 54be2ab4c7954ff42a2e1fd0a30d04947747a4d4 and subsequent commits.
